export function getImageUrl(filename) {
  const base = process.env.CLIENT_URL || "";
  return `${base}/images/${filename}`;
}

export const seedProducts = [
  {
    name: "Wireless Headphones",
    slug: "wireless-headphones",
    description:
      "Premium noise-canceling audio. Active noise cancellation with a premium acoustic architecture.",
    price: 89,
    category: "Electronics",
    image: "wireless-headphones-56586a.png",
    stock: 2,
    rating: 5,
    isNewArrival: true,
    isFeatured: true,
    isTrending: true,
  },
  {
    name: "Smart Watch",
    slug: "smart-watch",
    description:
      "Advanced health tracking wrapped in an elegant aerospace-grade aluminum case.",
    price: 149,
    originalPrice: 199,
    category: "Wearables",
    image: "smart-watch-56586a.png",
    stock: 42,
    rating: 5,
    isFeatured: true,
    isTrending: true,
  },
  {
    name: "Mechanical Keyboard",
    slug: "mechanical-keyboard",
    description:
      "Tactile precision for the modern workspace. Hot-swappable switches.",
    price: 99,
    category: "Electronics",
    image: "mechanical-keyboard-56586a.png",
    stock: 55,
    rating: 5,
    isTrending: true,
  },
  {
    name: "Gaming Mouse",
    slug: "gaming-mouse",
    description: "High precision, ergonomic design.",
    price: 49,
    category: "Electronics",
    image: "gaming-mouse-56586a.png",
    stock: 80,
    rating: 4,
    isFeatured: true,
  },
  {
    name: "Laptop Backpack",
    slug: "laptop-backpack",
    description: "Water-resistant, multiple compartments.",
    price: 59,
    category: "Accessories",
    image: "laptop-backpack-56586a.png",
    stock: 35,
    rating: 4,
    isFeatured: true,
  },
  {
    name: "Bluetooth Speaker",
    slug: "bluetooth-speaker",
    description: "Portable, 360-degree sound.",
    price: 79,
    category: "Electronics",
    image: "bluetooth-speaker-56586a.png",
    stock: 60,
    rating: 4,
    isFeatured: true,
  },
  {
    name: "Premium Linen Shirt",
    slug: "premium-linen-shirt",
    description: "Breathable premium linen crafted for everyday comfort.",
    price: 85,
    category: "Wearables",
    image: "premium-linen-shirt-56586a.png",
    stock: 25,
    rating: 5,
  },
  {
    name: "Artisan Ceramic Mug",
    slug: "artisan-ceramic-mug",
    description: "Hand-finished ceramic mug with a matte black glaze.",
    price: 24,
    category: "Accessories",
    image: "artisan-ceramic-mug-56586a.png",
    stock: 120,
    rating: 5,
  },
  {
    name: "Minimalist Smart Watch",
    slug: "minimalist-smart-watch",
    description: "Sleek smart watch with essential health tracking features.",
    price: 199.99,
    category: "Electronics",
    image: "smart-watch-56586a.png",
    stock: 42,
    rating: 5,
  },
  {
    name: "Premium Wireless Headphones",
    slug: "premium-wireless-headphones",
    description: "Studio-grade wireless headphones with adaptive noise canceling.",
    price: 249,
    category: "Electronics",
    image: "wireless-headphones-56586a.png",
    stock: 2,
    rating: 5,
  },
  {
    name: "Performance Running Shoe",
    slug: "performance-running-shoe",
    description: "Lightweight running shoe engineered for responsive comfort.",
    price: 129.5,
    category: "Wearables",
    image: "smart-watch-56586a.png",
    stock: 156,
    rating: 4,
  },
];

export const seedCategories = [
  {
    name: "Tech",
    slug: "tech",
    description: "Explore innovation.",
    image: "category-tech-56586a.png",
    filterCategory: "Electronics",
  },
  {
    name: "Lifestyle",
    slug: "lifestyle",
    description: "Curated for modern living.",
    image: "category-lifestyle-56586a.png",
    filterCategory: "Wearables",
  },
  {
    name: "Home Office",
    slug: "home-office",
    description: "Workspace essentials.",
    image: "category-home-office-56586a.png",
    filterCategory: "Accessories",
  },
];
